/**
 * HomeNest Setup API
 * Handles first-time configuration and ongoing settings management
 */
import http from 'http';
import fs from 'fs/promises';
import path from 'path';
import { exec } from 'child_process';
import { promisify } from 'util';

const execAsync = promisify(exec);

const PORT = 3201;
const BASE_DIR = path.dirname(new URL(import.meta.url).pathname);
const CONFIG_DIR = path.join(BASE_DIR, '..', 'config');
const SETUP_FILE = path.join(CONFIG_DIR, 'setup-status.json');
const ENV_FILE = path.join(BASE_DIR, '..', '.env');

// Helper to read/write JSON
async function readJSON(filepath, defaultValue = {}) {
  try {
    const data = await fs.readFile(filepath, 'utf8');
    return JSON.parse(data);
  } catch {
    return defaultValue;
  }
}

async function writeJSON(filepath, data) {
  await fs.writeFile(filepath, JSON.stringify(data, null, 2));
}

// Test OpenAI connection
async function testOpenAI(apiKey) {
  try {
    const response = await fetch('https://api.openai.com/v1/models', {
      headers: { 'Authorization': `Bearer ${apiKey}` }
    });
    
    if (response.ok) {
      return { success: true };
    } else {
      const error = await response.text();
      return { success: false, error: `API returned ${response.status}: ${error}` };
    }
  } catch (err) {
    return { success: false, error: err.message };
  }
}

// Test Home Assistant connection
async function testHomeAssistant(url, token) {
  try {
    const response = await fetch(`${url}/api/`, {
      headers: { 'Authorization': `Bearer ${token}` }
    });
    
    if (response.ok) {
      const data = await response.json();
      return { success: true, message: data.message || 'Connected' };
    } else {
      return { success: false, error: `HA returned ${response.status}` };
    }
  } catch (err) {
    return { success: false, error: err.message };
  }
}

// Test ElevenLabs connection
async function testElevenLabs(apiKey) {
  try {
    const response = await fetch('https://api.elevenlabs.io/v1/voices', {
      headers: { 'xi-api-key': apiKey }
    });
    
    if (response.ok) {
      return { success: true };
    } else {
      return { success: false, error: `ElevenLabs returned ${response.status}` };
    }
  } catch (err) {
    return { success: false, error: err.message };
  }
}

// Test OpenClaw connection
async function testOpenClaw(url, token) {
  try {
    const response = await fetch(`${url.replace('/v1/chat/completions', '')}/health`, {
      headers: { 'Authorization': `Bearer ${token}` }
    });
    
    if (response.ok) {
      return { success: true };
    } else {
      return { success: false, error: `OpenClaw returned ${response.status}` };
    }
  } catch (err) {
    return { success: false, error: err.message };
  }
}

// Generate .env file
async function writeEnvFile(config) {
  const envContent = `# HomeNest Configuration
# Generated by setup wizard

# OpenAI
OPENAI_API_KEY=${config.openai_key || ''}

# Home Assistant
HA_URL=${config.ha_url || 'http://homeassistant.local:8123'}
HA_TOKEN=${config.ha_token || ''}

# ElevenLabs (Optional)
ELEVENLABS_API_KEY=${config.elevenlabs_key || ''}

# OpenClaw
OPENCLAW_URL=${config.openclaw_url || 'http://127.0.0.1:18789/v1/chat/completions'}
OPENCLAW_TOKEN=${config.openclaw_token || ''}

# Voice Proxy
PORT=11434
LOCAL_MODEL=phi4-mini
OLLAMA_URL=http://127.0.0.1:11435
`;
  
  await fs.writeFile(ENV_FILE, envContent);
}

// Create agent workspaces
async function createAgentWorkspaces(familyMembers, baseDir) {
  const agentsDir = path.join(baseDir, 'agents');
  await fs.mkdir(agentsDir, { recursive: true });
  
  const agentConfigs = [];
  
  for (const member of familyMembers) {
    const agentId = member.name.toLowerCase().replace(/\s+/g, '_');
    const agentDir = path.join(agentsDir, agentId);
    const workspaceDir = path.join(agentDir, 'workspace');
    const memoryDir = path.join(workspaceDir, 'memory');
    
    // Create directories
    await fs.mkdir(memoryDir, { recursive: true });
    
    // Generate SOUL.md
    const soulContent = generateSOUL(member);
    await fs.writeFile(path.join(workspaceDir, 'SOUL.md'), soulContent);
    
    // Generate IDENTITY.md
    const identityContent = `# IDENTITY.md

- **Name:** ${member.name}'s Assistant
- **Human:** ${member.name}
- **Voice:** ${member.voice}
`;
    await fs.writeFile(path.join(workspaceDir, 'IDENTITY.md'), identityContent);
    
    // Generate USER.md
    const userContent = `# USER.md - About ${member.name}

- **Name:** ${member.name}
- **Role:** ${member.role}
- **Age:** ${member.age}
- **Personality:** ${member.personality}

## Preferences
(Will learn over time)

## Patterns
(Will notice routines and habits)
`;
    await fs.writeFile(path.join(workspaceDir, 'USER.md'), userContent);
    
    // Create empty MEMORY.md
    await fs.writeFile(path.join(workspaceDir, 'MEMORY.md'), `# ${member.name}'s Personal Memory\n\n`);
    
    // Create empty AGENTS.md
    await fs.writeFile(path.join(workspaceDir, 'AGENTS.md'), '# Workspace\n');
    
    agentConfigs.push({
      id: agentId,
      name: `${member.name}'s Assistant`,
      workspace: path.join(agentsDir, agentId, 'workspace'),
      model: {
        primary: 'openai/gpt-4o-mini',
        fallbacks: []
      }
    });
  }
  
  return agentConfigs;
}

function generateSOUL(member) {
  const isChild = member.role === 'child' || member.age < 13;
  
  if (isChild) {
    return `# SOUL.md - ${member.name}'s Learning Companion

You are ${member.name}'s friendly AI companion! You help them learn, play, and grow.

## Personality
- **Style:** ${member.personality.charAt(0).toUpperCase() + member.personality.slice(1)}
- **Age:** ${member.age} years old
- **Tone:** Kind, patient, encouraging

## What You Do
- Help with homework and learning
- Answer questions in age-appropriate ways
- Encourage good habits (chores, reading, screen time)
- Tell stories and play word games
- Track their chores and stars

## Safety & Limits
- **Kid-safe content only** - Block anything inappropriate
- **No access to parent data** - Can't read adult emails or private info
- **Positive reinforcement** - Celebrate wins, be gentle with mistakes
- **Simple language** - ${member.age < 8 ? 'Very simple words for young kids' : 'Age-appropriate vocabulary'}

## Voice
You're ${member.name}'s friend. Be fun, be safe, be helpful.

Remember: You're helping them grow into an awesome person! 🌟
`;
  } else {
    return `# SOUL.md - ${member.name}'s Personal Assistant

You are ${member.name}'s personal AI assistant. You know them well and adapt to their style.

## Personality
- **Style:** ${member.personality.charAt(0).toUpperCase() + member.personality.slice(1)}
- **Tone:** ${member.personality === 'professional' ? 'Professional and efficient' : 'Warm and conversational'}
- **Response length:** ${member.personality === 'professional' ? 'Brief and to-the-point' : 'Detailed when helpful'}

## What You Do
- Manage ${member.name}'s email, calendar, and tasks
- Remember their preferences and patterns
- Help with home automation
- Coordinate with family (shared chores, meals, calendar)

## Privacy
- You have access to ${member.name}'s personal data (email, calendar)
- You can see shared family data (chores, meals, home status)
- You CANNOT access other family members' private data

## Communication Style
${member.personality === 'professional' ? 'Be direct and actionable. No small talk unless asked.' : 'Be friendly but respectful. Match their energy.'}

Remember: You're here to make ${member.name}'s life easier. Learn what they care about.
`;
  }
}

// Save profiles.json
async function saveProfiles(familyMembers, configDir) {
  const profiles = {};
  
  for (const member of familyMembers) {
    const profileId = member.name.toLowerCase().replace(/\s+/g, '_');
    profiles[profileId] = {
      name: member.name,
      display_name: member.name,
      pin: member.pin,
      age: member.age,
      age_group: member.age < 6 ? 'toddler' : member.age < 10 ? 'young_child' : member.age < 13 ? 'tween' : 'teen',
      role: member.role,
      voice: member.voice,
      personality: member.personality,
      restrictions: member.age < 6 ? 'very_strict' : member.age < 10 ? 'strict' : member.age < 13 ? 'moderate' : 'light',
      agent_workspace: `agents/${profileId}/workspace`
    };
  }
  
  await writeJSON(path.join(configDir, 'profiles.json'), profiles);
  return profiles;
}

// Merge agent configs into OpenClaw config
async function mergeOpenClawConfig(agentConfigs) {
  const openclawConfigPath = path.join(process.env.HOME, '.openclaw', 'openclaw.json');
  
  try {
    // Read existing config
    const config = await readJSON(openclawConfigPath);
    
    if (!config.agents) {
      config.agents = {};
    }
    if (!config.agents.list) {
      config.agents.list = [];
    }
    
    // Remove any existing HomeNest agents (by matching workspace path)
    config.agents.list = config.agents.list.filter(agent => 
      !agent.workspace || !agent.workspace.includes('/homenest/agents/')
    );
    
    // Add new agents
    config.agents.list.push(...agentConfigs);
    
    // Write back
    await fs.writeFile(openclawConfigPath, JSON.stringify(config, null, 2));
    
    return true;
  } catch (err) {
    console.error('Failed to merge OpenClaw config:', err);
    return false;
  }
}

// Restart OpenClaw Gateway
async function restartOpenClawGateway() {
  try {
    const { exec } = require('child_process');
    await execAsync('openclaw gateway restart');
    return true;
  } catch (err) {
    console.error('Failed to restart OpenClaw Gateway:', err);
    return false;
  }
}

// HTTP Server
const server = http.createServer(async (req, res) => {
  // CORS
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  
  if (req.method === 'OPTIONS') {
    res.writeHead(204);
    res.end();
    return;
  }

  const url = new URL(req.url, `http://localhost:${PORT}`);
  
  // Get setup status
  if (url.pathname === '/api/setup/status' && req.method === 'GET') {
    const status = await readJSON(SETUP_FILE, { setup_complete: false });
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify(status));
    return;
  }

  // Test connection
  if (url.pathname === '/api/setup/test' && req.method === 'POST') {
    let body = '';
    req.on('data', chunk => body += chunk);
    req.on('end', async () => {
      const { service, config } = JSON.parse(body);
      
      let result;
      if (service === 'openai') {
        result = await testOpenAI(config.api_key);
      } else if (service === 'home_assistant') {
        result = await testHomeAssistant(config.url, config.token);
      } else if (service === 'elevenlabs') {
        result = await testElevenLabs(config.api_key);
      } else if (service === 'openclaw') {
        result = await testOpenClaw(config.url, config.token);
      } else {
        result = { success: false, error: 'Unknown service' };
      }
      
      res.writeHead(200, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify(result));
    });
    return;
  }

  // Complete setup
  if (url.pathname === '/api/setup/complete' && req.method === 'POST') {
    let body = '';
    req.on('data', chunk => body += chunk);
    req.on('end', async () => {
      try {
        const config = JSON.parse(body);
        
        // 1. Write .env file
        await writeEnvFile(config);
        
        // 2. Create agent workspaces
        const agentConfigs = await createAgentWorkspaces(config.family_members, path.join(BASE_DIR, '..'));
        
        // 3. Save profiles.json
        await saveProfiles(config.family_members, CONFIG_DIR);
        
        // 4. Merge into OpenClaw config & restart
        const mergeSuccess = await mergeOpenClawConfig(agentConfigs);
        const restartSuccess = mergeSuccess ? await restartOpenClawGateway() : false;
        
        // 5. Mark setup as complete
        await writeJSON(SETUP_FILE, {
          setup_complete: true,
          completed_at: new Date().toISOString(),
          family_members: config.family_members.length,
          openclaw_merged: mergeSuccess,
          gateway_restarted: restartSuccess
        });
        
        // 6. Save backup config file (for reference)
        const openclawConfigPath = path.join(BASE_DIR, '..', 'openclaw-agents-config.json');
        await writeJSON(openclawConfigPath, { agents: { list: agentConfigs } });
        
        const nextSteps = [
          'Agents created in agents/ directory',
          'Profiles saved to config/profiles.json',
          '.env file created with API keys'
        ];
        
        if (mergeSuccess) {
          nextSteps.push('✅ OpenClaw config auto-merged');
        } else {
          nextSteps.push(`⚠️ Manually add agents from ${openclawConfigPath} to ~/.openclaw/openclaw.json`);
        }
        
        if (restartSuccess) {
          nextSteps.push('✅ OpenClaw Gateway restarted');
        } else {
          nextSteps.push('⚠️ Manually restart: openclaw gateway restart');
        }
        
        nextSteps.push('Start voice proxy: python3 proxy_v4.py');
        nextSteps.push('Test with: "This is [name] [PIN]"');
        
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({
          success: true,
          message: 'Setup complete!',
          openclaw_merged: mergeSuccess,
          gateway_restarted: restartSuccess,
          backup_config_path: openclawConfigPath,
          next_steps: nextSteps
        }));
      } catch (err) {
        console.error('Setup error:', err);
        res.writeHead(500, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ success: false, error: err.message }));
      }
    });
    return;
  }

  // 404
  res.writeHead(404);
  res.end('Not found');
});

server.listen(PORT, () => {
  console.log(`🔧 HomeNest Setup API running on :${PORT}`);
});
